[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@solmate/=lib/solmate/src/"
]

compiler = "0.8.28"

[rpc_endpoints]
world_chain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

# Note: World Chain Sepolia uses Alchemy's block explorer infrastructure
# For contract verification, use the blockscout verifier with the correct API endpoint
# [etherscan]
# world_chain_sepolia = { key = "${WORLDSCAN_API_KEY}", url = "https://sepolia.worldscan.io/api", chain = 4801 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
